export const BIRD_LABELS = [
  "Aigrette garzette",
  "Alouette des champs",
  "Bihoreau gris",
  "Bruant jaune",
  "Buse variable",
  "Canard colvert",
  "Chardonneret élégant",
  "Choucas des tours",
  "Chouette hulotte",
  "Corbeau freux",
  "Corneille mantelée",
  "Corneille noire",
  "Cygne tuberculé",
  "Épervier d'Europe",
  "Étourneau sansonnet",
  "Faucon crécerelle",
  "Fauvette à tête noire",
  "Fauvette grisette",
  "Foulque macroule",
  "Gallinule poule d'eau",
  "Geai des chênes",
  "Goéland argenté",
  "Grand corbeau",
  "Grand cormoran",
  "Grande aigrette",
  "Grèbe castagneux",
  "Grèbe huppé",
  "Grimpereau des jardins",
  "Grive draine",
  "Grive mauvis",
  "Grive musicienne",
  "Héron cendré",
  "Hibou moyen-duc",
  "Linotte mélodieuse",
  "Martin-pêcheur",
  "Merle noir",
  "Mésange bleue",
  "Mésange boréale",
  "Mésange charbonnière",
  "Mésange huppée",
  "Mésange noire",
  "Mésange nonnette",
  "Moineau domestique",
  "Moineau friquet",
  "Mouette rieuse",
  "Pas un oiseau",
  "Pic épeiche",
  "Pic vert",
  "Pie bavarde",
  "Pigeon biset",
  "Pigeon colombin",
  "Pigeon ramier",
  "Pinson des arbres",
  "Rougegorge familier",
  "Sittelle torchepot",
  "Tourterelle des bois",
  "Tourterelle turque",
  "Troglodyte mignon",
  "Verdier d'Europe",
];
